apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: fg-app
  name: nodejs
  namespace: dsantra12
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: nodejs
status:
  loadBalancer: {}
